### ISSUE TITLE
Could not connect to lockdownd. Exiting.: Resource temporarily unavailable

### ISSUE THREAD

**Issue by bartonhammond** [google/ios-webkit-debug-proxy#244]
*  Mac 10.13.3
*  version
```
$ ios_webkit_debug_proxy --version
ios_webkit_debug_proxy 1.8
Built with libimobiledevice v1.2.0, libplist v2.0.0
```
*  console log
```
barton@BMac tempAutomate (master) $ ios_webkit_debug_proxy -c 6cab51ed4852049ade8d8d0f808b842bd12f0d0e:27753 -d
ss.add_fd(3)
ss.recv fd=3 len=294
ss.recv fd=3 len=684
ss.add_server_fd(4)
Could not connect to lockdownd. Exiting.: Resource temporarily unavailable
ss.remove_server_fd(4)
Unable to attach 6cab51ed4852049ade8d8d0f808b842bd12f0d0e inspector
^Css.remove_fd(3)
```

**Comment by artygus** [comment]
hi @bartonhammond, please use search, there were similar issues, most likely 

    brew update
    brew reinstall --HEAD libimobiledevice
    brew reinstall -s ios-webkit-debug-proxy

should help you

**Comment by bartonhammond** [comment]
@artygus  thanks for your quick response!  That fixed it.

I did [search issues](https://github.com/google/ios-webkit-debug-proxy/issues?utf8=%E2%9C%93&q=is%3Aissue+resource++unavailable) and found nothing containing "resource unavailable".  I looked through some issues and I don't know enough to ascertain one problem is same as some other.  I already addressed a permission issue which was resolved w/ a `chmod` cmd.

**Comment by rahulbasu86** [comment]
@bartonhammond @artygus 

I am also facing the same problem:

MAC OS: 10.13.6
IOS: 12.1.4

$ ios_webkit_debug_proxy --version
ios_webkit_debug_proxy 1.8.3
Built with libimobiledevice v1.2.0, libplist v2.0.0


$ ios_webkit_debug_proxy -c ce7f7b5040390560fb09c588221de8ecbfda0d24 -d

ss.add_fd(3)
ss.recv fd=3 len=294
ss.recv fd=3 len=684
^Css.remove_fd(3)

I tried the below steps also:

brew update
brew reinstall --HEAD libimobiledevice
brew reinstall -s ios-webkit-debug-proxy
But when i do "brew reinstall --HEAD libimobiledevice" i get invalid option : --HEAD

**Comment by artygus** [comment]
hi @rahulbasu86, you could try

    brew uninstall libimobiledevice
    brew install --HEAD libimobiledevice

please use `man brew` for more information on how to work with brew

**Comment by rahulbasu86** [comment]
@argelius 
I am still getting the below error:

ios_webkit_debug_proxy -c ce7f7b5040390560fb09c588221de8ecbfda0d24:27753 -d
ss.add_fd(3)
ss.recv fd=3 len=294
ss.recv fd=3 len=684
ss.add_server_fd(4)
Could not connect to lockdownd, error code -17. Exiting.
ss.remove_server_fd(4)
Unable to attach ce7f7b5040390560fb09c588221de8ecbfda0d24 inspector

**Comment by artygus** [comment]
error -17 corresponds to LOCKDOWN_E_PASSWORD_PROTECTED, which mean you need to enter passcode? and maybe retry running the app

**Comment by rahulbasu86** [comment]
@artygus 
Thanks for your help.

now i am getting the below error:

ios_webkit_debug_proxy -c ce7f7b5040390560fb09c588221de8ecbfda0d24:27753 -d
ss.add_fd(3)
ss.recv fd=3 len=294
ss.recv fd=3 len=684
ss.add_server_fd(4)
Could not connect to lockdownd, error code -21. Exiting.
ss.remove_server_fd(4)
Unable to attach ce7f7b5040390560fb09c588221de8ecbfda0d24 inspector

**Comment by artygus** [comment]
it supposed to mean device is not paired, for further references on error codes you can checkout libimobildevice repo https://github.com/libimobiledevice/libimobiledevice/blob/master/include/libimobiledevice/lockdown.h#L37
